package login_register_with_text_file;

import login_register_with_text_file.Message_Frame;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1BestCsharp
 */
public class Login_And_Register extends javax.swing.JFrame {

    ArrayList<Patient> patients;
    /**
     * Creates new form Login_And_Register
     */
    // create a border for the jpanel
    Border panel_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
    // create a border for the textfields
    Border textfields_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white);
    // optional red border
    Border textfields_red_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);
    // create a border for the jlabels
    Border lbl_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.lightGray);
    // the file path -> C:\Users\1BestCsharp\Desktop\java_app

    // array of all usernames
    ArrayList<String> all_usernames = new ArrayList<>();

    // the message frame
    Message_Frame msgF = new Message_Frame();
    
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public Login_And_Register() {
        initComponents();
        patients = new ArrayList<Patient>();

        // image link: https://pixabay.com/vectors/cross-no-x-forbidden-closed-42928/
        // display close images in jlabel
        displayImage();

        // center the form
        this.setLocationRelativeTo(null);

        // set borders
        jPanel_main.setBorder(panel_border);
        jLabel_login_title.setBorder(lbl_border);
        tf_PatientLoginId.setBorder(textfields_border);
        tf_LoginPatientPassword.setBorder(textfields_border);

        // test
        /*
        for(String uname:all_usernames)
        {
            System.out.println(uname);
        }
         */
    }

    public void populateArrayList() {
        
        try {
            FileInputStream fileEmployee = new FileInputStream("Patients.dat");
            ObjectInputStream inputFileEmployee = new ObjectInputStream(fileEmployee);
            boolean endOfFile = false;
            while (!endOfFile) {
                try {
                    patients.add((Patient) inputFileEmployee.readObject());
                } catch (EOFException e) {
                    endOfFile = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFileEmployee.close();            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // create a function to check if the username already exist
    public boolean checkIfUsernameExist(String un) {
        boolean exist = false;
        
        for (String username : all_usernames) {
            if (username.equals(un)) {
                exist = true;
            }
        }
        
        return exist;
    }

    // function to display image
    public void displayImage() {
        ImageIcon imgico = new ImageIcon(getClass().getResource("\\/images/x.png"));
        Image img = imgico.getImage().getScaledInstance(jLabel_close_.getWidth(), jLabel_close_.getHeight(), Image.SCALE_SMOOTH);
        jLabel_close_.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jLabel_close_ = new javax.swing.JLabel();
        jLabel_login_title = new javax.swing.JLabel();
        jPanel_username = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_PatientLoginId = new javax.swing.JTextField();
        jPanel_password = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_LoginPatientPassword = new javax.swing.JPasswordField();
        jButton_login_ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setUndecorated(true);

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_close_.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_close_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_close_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close_.setOpaque(true);
        jLabel_close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close_MouseClicked(evt);
            }
        });

        jLabel_login_title.setFont(new java.awt.Font("Vijaya", 0, 66)); // NOI18N
        jLabel_login_title.setText("Login");

        jPanel_username.setBackground(new java.awt.Color(194, 177, 163));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        tf_PatientLoginId.setBackground(new java.awt.Color(194, 177, 163));
        tf_PatientLoginId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_PatientLoginId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_PatientLoginIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_usernameLayout = new javax.swing.GroupLayout(jPanel_username);
        jPanel_username.setLayout(jPanel_usernameLayout);
        jPanel_usernameLayout.setHorizontalGroup(
            jPanel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usernameLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tf_PatientLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_usernameLayout.setVerticalGroup(
            jPanel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usernameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_PatientLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel_password.setBackground(new java.awt.Color(194, 177, 163));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        tf_LoginPatientPassword.setBackground(new java.awt.Color(194, 177, 163));
        tf_LoginPatientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LoginPatientPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_passwordLayout = new javax.swing.GroupLayout(jPanel_password);
        jPanel_password.setLayout(jPanel_passwordLayout);
        jPanel_passwordLayout.setHorizontalGroup(
            jPanel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_passwordLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tf_LoginPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_passwordLayout.setVerticalGroup(
            jPanel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_passwordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_LoginPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton_login_.setBackground(new java.awt.Color(0, 0, 0));
        jButton_login_.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_login_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login_.setText("Login");
        jButton_login_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_ActionPerformed(evt);
            }
        });

        jButton1.setText("you can register here ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                        .addComponent(jLabel_login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel_close_, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_login_, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_mainLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel_login_title, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel_close_, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jPanel_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_login_, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new RegisterPage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_login_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_ActionPerformed
        populateArrayList();
        String Id = tf_PatientLoginId.getText().trim();
        String Password = tf_LoginPatientPassword.getText().trim();
        boolean ret = false;
        
        boolean denem = false;
        for (int i = 0; i < patients.size(); i++) {
            System.out.println(patients.get(i).getName());
            
            if (patients.get(i).getıd().compareTo(Id) == 0 && patients.get(i).getpassword().compareTo(Password) == 0) {
                ret = true;
                
                AppointmentTimes aptime = new AppointmentTimes();
                
                aptime.getname.setText(patients.get(i).getName());
                aptime.jLabel13.setText(patients.get(i).getıd());
                aptime.jLabel18.setText(patients.get(i).getEmail());
                aptime.jLabel20.setText(patients.get(i).getage());
                aptime.jLabel21.setText(patients.get(i).getpassword());
                
                aptime.setVisible(true);
                denem = false;
                close();
                break;
                
            } else {
                
                denem = true;
            }
        }
        msgF.jLabel_Title.setText("Signup Error");
        msgF.jLabel_message.setText("Something Wrong With Your identity");
        if (denem == true) {
            msgF.setVisible(true);
        } else {
            msgF.setVisible(false);
        }
        

    }//GEN-LAST:event_jButton_login_ActionPerformed

    private void tf_LoginPatientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LoginPatientPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LoginPatientPasswordActionPerformed

    private void tf_PatientLoginIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_PatientLoginIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_PatientLoginIdActionPerformed

    private void jLabel_close_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close_MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_close_MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Users_select user= new Users_select();
        user.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_And_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_And_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_And_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_And_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_And_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_login_;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_close_;
    private javax.swing.JLabel jLabel_login_title;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_password;
    private javax.swing.JPanel jPanel_username;
    private javax.swing.JPasswordField tf_LoginPatientPassword;
    private javax.swing.JTextField tf_PatientLoginId;
    // End of variables declaration//GEN-END:variables
}
