
package login_register_with_text_file;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cemil Can
 */
public class RegisterPage extends javax.swing.JFrame {
    ArrayList<Patient> patients;
        Message_Frame msgF = new Message_Frame();
        


    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        patients = new ArrayList<Patient>();
    }
    public void populateArrayList(){
        
        try {
            FileInputStream fileEmployee = new FileInputStream("Patients.dat");
            ObjectInputStream inputFileEmployee = new ObjectInputStream(fileEmployee);
            
            boolean endOfFile = false;
            while (!endOfFile){
                try {
                    patients.add((Patient) inputFileEmployee.readObject());
                } catch (EOFException e){
                    endOfFile = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFileEmployee.close();            
        } catch (IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    public void saveEmployeesToFile(){
        try {
            FileOutputStream fileEmployee = new FileOutputStream("Patients.dat");
            ObjectOutputStream outputFileEmployee = new ObjectOutputStream(fileEmployee);
            
            for (int i = 0; i<patients.size(); i++){
                outputFileEmployee.writeObject(patients.get(i));
            }
            outputFileEmployee.close();
            msgF.jLabel_message.setText("Successfully saved!");
            msgF.setVisible(true);


        } catch (IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_RegisterPatientId = new javax.swing.JTextField();
        tf_RegisterPatientFullname = new javax.swing.JTextField();
        tf_RegisterPatientAge = new javax.swing.JTextField();
        tf_RegisterPatientEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_RegisterPatientPassword = new javax.swing.JPasswordField();
        tf_RegisterPatientConfirmPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tf_RegisterPatientFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_RegisterPatientFullnameActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("FullName:");

        jLabel3.setText("Age:");

        jLabel4.setText("EMail:");

        jLabel5.setText("Password:");

        jLabel6.setText("Comfirm Password:");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf_RegisterPatientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_RegisterPatientPasswordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Register");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(tf_RegisterPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_RegisterPatientFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_RegisterPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_RegisterPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_RegisterPatientConfirmPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_RegisterPatientPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_RegisterPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_RegisterPatientFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_RegisterPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_RegisterPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_RegisterPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_RegisterPatientConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_RegisterPatientFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_RegisterPatientFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_RegisterPatientFullnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateArrayList();
        boolean ret = false;
        String Id2=tf_RegisterPatientId.getText();
        
        for(int i = 0; i < patients.size(); i++){
            if(patients.get(i).getıd().compareTo(Id2) == 0){
                ret = true;
            break;
            }
       
        }
        
        if(ret == true) {
            msgF.jLabel_message.setText("this ıd already signed up ");
            msgF.setVisible(true);
        }
        else {
            if (this.tf_RegisterPatientId.getText().isEmpty() || 
                this.tf_RegisterPatientFullname.getText().isEmpty() ||
                this.tf_RegisterPatientAge.getText().isEmpty() || this.tf_RegisterPatientEmail.getText().isEmpty() || this.tf_RegisterPatientPassword.getText().isEmpty()
                 || this.tf_RegisterPatientConfirmPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the details");
        }
         else if(!this.tf_RegisterPatientPassword.getText().trim().equals(this.tf_RegisterPatientConfirmPassword.getText())){
         
                    msgF.jLabel_Title.setText("Register Error");
                    msgF.jLabel_message.setText("Passwords do not confirm");
                    msgF.setVisible(true);
         }
         else {
            String Id = tf_RegisterPatientId.getText().trim();
            String Fullname = tf_RegisterPatientFullname.getText().trim();
            String Age = tf_RegisterPatientAge.getText().trim();
            String Email = tf_RegisterPatientEmail.getText().trim();
            String Password = tf_RegisterPatientPassword.getText().trim();

            
            Patient emp = new Patient(Id,Fullname,Age,Email,Password);
            patients.add(emp);
            
            saveEmployeesToFile();

        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_RegisterPatientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_RegisterPatientPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_RegisterPatientPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_RegisterPatientAge;
    private javax.swing.JPasswordField tf_RegisterPatientConfirmPassword;
    private javax.swing.JTextField tf_RegisterPatientEmail;
    private javax.swing.JTextField tf_RegisterPatientFullname;
    private javax.swing.JTextField tf_RegisterPatientId;
    private javax.swing.JPasswordField tf_RegisterPatientPassword;
    // End of variables declaration//GEN-END:variables
}
